
import React, { useState, useEffect } from 'react';
import { Layout } from './components/Layout';
import { PostGenerator } from './components/PostGenerator';
import { PostCard } from './components/PostCard';
import { GameSimulator } from './components/GameSimulator';
import { GeneratedPost, GameTrigger } from './types';
import { GeminiService } from './services/geminiService';

const App: React.FC = () => {
  const [posts, setPosts] = useState<GeneratedPost[]>([]);
  const [activeTrigger, setActiveTrigger] = useState<GameTrigger | null>(null);
  const [autoGenerating, setAutoGenerating] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('superbowl_posts');
    if (saved) {
      try { setPosts(JSON.parse(saved)); } catch (e) { console.error(e); }
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('superbowl_posts', JSON.stringify(posts));
  }, [posts]);

  const handlePostGenerated = (post: GeneratedPost) => {
    setPosts([post, ...posts]);
  };

  const handleTrigger = async (trigger: GameTrigger) => {
    setActiveTrigger(trigger);
    
    // Auto-generate if it's a priority event
    if (trigger.priority >= 5) {
      setAutoGenerating(true);
      try {
        const options = {
          prompt: trigger.context?.raw_text || trigger.trigger_type,
          style: 'Hype' as const,
          platform: 'Instagram' as const,
          contentType: 'Image' as const,
          gameEvent: trigger.trigger_type.toLowerCase(),
          engagementMode: 'Viral' as const,
          contextData: trigger.context
        };

        const { caption, hashtags, chatbotKeyword } = await GeminiService.generateCaption(options);
        const imageUrl = await GeminiService.generateImage(options);

        const newPost: GeneratedPost = {
          id: Math.random().toString(36).substr(2, 9),
          caption,
          hashtags,
          imageUrl,
          style: options.style,
          platform: options.platform,
          timestamp: Date.now(),
          eventLabel: trigger.trigger_type,
          engagementMode: options.engagementMode,
          chatbotKeyword,
          isAutoGenerated: true
        };

        setPosts(prev => [newPost, ...prev]);
      } catch (e) {
        console.error("Auto-gen failed", e);
      } finally {
        setAutoGenerating(false);
      }
    }

    // Dismiss trigger alert after 8 seconds
    setTimeout(() => setActiveTrigger(null), 8000);
  };

  return (
    <Layout>
      {/* Active Trigger Ping Overlay */}
      {activeTrigger && (
        <div className="fixed top-24 left-1/2 -translate-x-1/2 z-[100] w-[90%] max-w-xl">
           <div className="bg-red-600 rounded-3xl p-6 shadow-[0_0_50px_rgba(220,38,38,0.6)] border-2 border-white/20 animate-bounce">
              <div className="flex items-center gap-4">
                <div className="text-4xl">🚨</div>
                <div>
                  <h3 className="text-white font-oswald font-bold text-xl uppercase italic tracking-tighter">GAME TRIGGER DETECTED</h3>
                  <p className="text-red-100 text-sm font-bold uppercase tracking-widest">
                    {activeTrigger.trigger_type}: {activeTrigger.context?.raw_text || 'Score Updated'}
                  </p>
                  {autoGenerating && (
                    <p className="text-white/60 text-[10px] mt-2 font-black uppercase tracking-[0.2em] animate-pulse">
                      Generating AI Playbook in background...
                    </p>
                  )}
                </div>
              </div>
           </div>
        </div>
      )}

      <div className="space-y-12">
        <section className="text-center space-y-4 max-w-3xl mx-auto pt-8">
          <div className="inline-block px-3 py-1 rounded-full border border-red-500/30 bg-red-500/10 text-red-500 text-xs font-bold tracking-[0.2em] mb-4">
            SUPER BOWL LIX COMMAND CENTER
          </div>
          <h1 className="text-5xl md:text-7xl font-oswald font-bold leading-tight uppercase">
            LIVE <span className="text-nfl-red">BROADCAST</span> AI
          </h1>
        </section>

        {/* Simulator Dashboard */}
        <div className="max-w-4xl mx-auto">
           <GameSimulator onTrigger={handleTrigger} />
        </div>

        {/* Generator */}
        <div className="max-w-4xl mx-auto">
          <PostGenerator onPostGenerated={handlePostGenerated} />
        </div>

        {/* Feed */}
        <section className="space-y-8">
          <div className="flex items-center justify-between border-b border-white/10 pb-4">
            <h2 className="text-2xl font-oswald font-bold flex items-center gap-2">
              <span className="text-red-500">LIVE</span> FEED
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {posts.map((post) => (
              <PostCard key={post.id} post={post} />
            ))}
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default App;
