
export type PostStyle = 'Hype' | 'Funny' | 'Analytical' | 'Controversial' | 'Nostalgic';
export type Platform = 'X' | 'Instagram' | 'LinkedIn' | 'Threads';
export type ContentType = 'Image' | 'Video' | 'TextOnly';
export type EngagementMode = 'Viral' | 'Prediction';

export interface GameTrigger {
  trigger_type: string;
  period: number;
  clock: string;
  context: any;
  priority: number;
  ttl_seconds: number;
  id?: string;
}

export interface GeneratedPost {
  id: string;
  caption: string;
  hashtags: string[];
  imageUrl?: string;
  videoUrl?: string;
  style: PostStyle;
  platform: Platform;
  timestamp: number;
  eventLabel?: string;
  engagementMode: EngagementMode;
  chatbotKeyword?: string;
  isAutoGenerated?: boolean;
}

export interface GeneratorOptions {
  prompt: string;
  style: PostStyle;
  platform: Platform;
  contentType: ContentType;
  gameEvent: string;
  engagementMode: EngagementMode;
  contextData?: any;
}
