
import React from 'react';
import { GeneratedPost } from '../types';

interface Props {
  post: GeneratedPost;
}

export const PostCard: React.FC<Props> = ({ post }) => {
  const deployToInstagram = () => {
    const text = `${post.caption}\n\n${post.hashtags.map(t => `#${t.replace('#','')}`).join(' ')}`;
    
    // 1. Copy to clipboard
    navigator.clipboard.writeText(text).then(() => {
      // 2. Alert user
      alert('Play copied to clipboard! Opening Instagram...');
      
      // 3. Attempt deep link or open web
      if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
        window.location.href = "instagram://camera";
      } else {
        window.open("https://www.instagram.com", "_blank");
      }
    });
  };

  const isPrediction = post.engagementMode === 'Prediction';

  return (
    <div className={`glass rounded-[2rem] overflow-hidden group hover:border-white/30 transition-all duration-500 border-2 ${
      isPrediction ? 'border-blue-500/40 shadow-[0_0_40px_rgba(59,130,246,0.15)]' : 'border-white/5'
    } ${post.isAutoGenerated ? 'border-red-500/40' : ''}`}>
      {/* Media Preview */}
      <div className="aspect-square bg-black relative overflow-hidden">
        {post.videoUrl ? (
          <video src={post.videoUrl} controls autoPlay loop muted className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-[2000ms]" />
        ) : post.imageUrl ? (
          <img src={post.imageUrl} alt="Super Bowl Scene" className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-[2000ms]" />
        ) : (
          <div className="flex items-center justify-center h-full text-slate-800 font-oswald text-4xl">DRAFT</div>
        )}
        
        {/* Status Overlays */}
        <div className="absolute top-5 left-5 flex flex-col gap-3">
          <div className="flex gap-2">
            <span className="px-3 py-1 bg-red-600 backdrop-blur-md rounded-full text-[10px] font-black uppercase tracking-[0.1em] text-white shadow-lg">
              {post.platform}
            </span>
            {post.isAutoGenerated && (
              <span className="px-3 py-1 bg-yellow-500 backdrop-blur-md rounded-full text-[10px] font-black uppercase tracking-[0.1em] text-black shadow-lg">
                AUTO-PLAY
              </span>
            )}
          </div>
          <span className="px-3 py-1 bg-black/70 backdrop-blur-md rounded-full text-[10px] font-black uppercase tracking-[0.1em] text-white border border-white/20">
            {post.eventLabel || 'CUSTOM'}
          </span>
        </div>

        {/* Chatbot Trigger */}
        {post.chatbotKeyword && (
          <div className="absolute bottom-4 inset-x-4">
             <div className="bg-black/80 backdrop-blur-xl border border-white/10 rounded-2xl p-3 flex items-center justify-between">
               <div className="flex flex-col">
                 <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest">Automation</span>
                 <span className="text-xs font-oswald font-bold text-white tracking-wider uppercase">Comment "{post.chatbotKeyword}"</span>
               </div>
               <div className="bg-blue-600 p-2 rounded-lg">
                 <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                   <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
                 </svg>
               </div>
             </div>
          </div>
        )}
      </div>

      <div className="p-7">
        <p className="text-sm text-slate-200 leading-relaxed mb-6 whitespace-pre-wrap font-medium h-[4.5em] overflow-hidden">
          {post.caption}
        </p>
        
        <div className="flex items-center justify-between pt-6 border-t border-white/5">
          <div className="flex flex-col">
             <span className="text-[10px] font-black text-white uppercase tracking-wider">Deploy Ready</span>
             <span className="text-[9px] text-slate-500 font-bold uppercase">
               {new Date(post.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
             </span>
          </div>
          <button
            onClick={deployToInstagram}
            className="flex items-center gap-2 px-6 py-2.5 rounded-2xl bg-gradient-to-r from-purple-600 to-red-600 text-white hover:scale-105 transition-all text-[11px] font-black uppercase tracking-[0.1em] shadow-lg shadow-purple-900/30 active:scale-95"
          >
            Deploy Play
          </button>
        </div>
      </div>
    </div>
  );
};
